// <auto-generated />
using System;
using Eksamen2024.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eksamen2024.Migrations
{
    [DbContext(typeof(ItemDbContext))]
    partial class ItemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Eksamen2024.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PinpointId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsersUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CommentId");

                    b.HasIndex("PinpointId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Eksamen2024.Models.Pinpoint", b =>
                {
                    b.Property<int>("PinpointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsersUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PinpointId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("Pinpoints");
                });

            modelBuilder.Entity("Eksamen2024.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Eksamen2024.Models.Comment", b =>
                {
                    b.HasOne("Eksamen2024.Models.Pinpoint", "Pinpoint")
                        .WithMany("Comments")
                        .HasForeignKey("PinpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eksamen2024.Models.Users", "Users")
                        .WithMany("Comments")
                        .HasForeignKey("UsersUserId");

                    b.Navigation("Pinpoint");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Eksamen2024.Models.Pinpoint", b =>
                {
                    b.HasOne("Eksamen2024.Models.Users", "Users")
                        .WithMany("Pinpoint")
                        .HasForeignKey("UsersUserId");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Eksamen2024.Models.Pinpoint", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Eksamen2024.Models.Users", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Pinpoint");
                });
#pragma warning restore 612, 618
        }
    }
}
